# Generated by Django 5.0.2 on 2024-02-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_directionschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MondaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='День недели для расписания')),
                ('direction_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_choice', to='base.directionschedule', verbose_name='Выбрать направление')),
            ],
            options={
                'verbose_name': '2) День недели Понедельник',
                'verbose_name_plural': '2) Дни недели Понедельник',
            },
        ),
        migrations.DeleteModel(
            name='WeekSchedule',
        ),
    ]
