# Generated by Django 5.0.2 on 2024-02-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mondayschedule_delete_weekschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dayofweek')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.timeslot')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trainer')),
            ],
        ),
        migrations.DeleteModel(
            name='MondaySchedule',
        ),
    ]
